package com.ia.recog_track;

import org.json.JSONObject;

import java.util.HashMap;
import java.util.Map;

public class Linhas {
    Linhas(){}
   public String[] getMap(){
        String[] list = {
                "001 : Saré - 40 Horas",
                "004 : Júlia Seffer - Cidade Nova",
                "005 : Marituba - Centro",
                "011 : Júlia Seffer - Castanheira",
                "014 : Águas Brancas - Cidade Nova",
                "015 : 40 Horas - Castanheira",
                "021 : Guanabara - Centro",
                "113 : Cremação - Estrada Nova",
                "114 : Cremação - Alcindo Cacela",
                "226 : Bengui - Ver-o-Peso",
                "227 : Sacramenta - Humaitá",
                "228 : Sacramenta - São Brás",
                "229 : Pedreira - Condor",
                "230 : Marex - Privilégio",
                "237 : Sacramenta - Pres. Vargas",
                "305 : UFPA - Icoaraci",
                "306 : UFPA - Pedreira",
                "307 : UFPA - Padre Eutíquio",
                "308 : UFPA - Alcindo Cacela",
                "309 : UFPA - Ver-o-Peso",
                "310 : UFPA - Pres. Vargas",
                "311 : Guamá - Conselheiro",
                "312 : Guamá - Montepio",
                "314 : Guamá - Ver-o-Peso",
                "315 : UFPA - Centro Histórico",
                "316 : Guamá - Pres. Vargas",
                "317 : Guamá - Pátio Belém",
                "318 : Arsenal",
                "320 : UFPA - Tamoios",
                "321 : UFPA - Cidade Nova 6",
                "323 : Canudos - Praça Amazonas",
                "324 : Canudos - Ver-o-Peso",
                "325 : Canudos - Ver-o-Peso (via Gentil)",
                "326 : Canudos - Prado II",
                "328 : Cipriano Santos - Presidente Vargas",
                "417 : Alcindo Cacela - José Malcher",
                "422 : Domingos Marreiros - Ver-o-Peso",
                "439 : Pedreira - Nazaré",
                "441 : Ceasa - Felipe Patroni",
                "442 : Ceasa - Ver-o-Peso",
                "443 : Pedreira - Lomas (Linha A)",
                "445 : Pedreira - Lomas (Seletivo)",
                "446 : João Paulo II - Ver-o-Peso",
                "546 : Sacramenta - Nazaré",
                "547 : Médici - Presidente Vargas",
                "548 : Marambaia - Ver-o-Peso",
                "549 : Djalma Dutra",
                "631 : Marex - Ver-o-Peso",
                "632 : Marex - Felipe Patroni",
                "634 : Marex - Arsenal",
                "635 : CDP/Providência - Ver-o-Peso",
                "636 : Marex - Pres. Vargas",
                "638 : Marex - Bengui",
                "639 : Pratinha - Castanheira",
                "642 : Marex - Centro (Via Nazaré)",
                "643 : Pratinha - Ver-o-Peso",
                "663 : Bengui - Felipe Patroni",
                "664 : Bengui - Pátio Belém",
                "665 : Cordeiro de Farias - Pres. Vargas (Via BRT)",
                "666 : Canarinho - Pres. Vargas",
                "667 : Cordeiro de Farias - Ver-o-Peso (Via BRT)",
                "669 : Cordeiro de Farias - Castanheira",
                "754 : Jardim Sideral - Ver-o-Peso",
                "755 : Sideral - Pátio Belém",
                "756 : Jardelândia - Centro",
                "757 : A Jardim Europa - Presidente Vargas",
                "757 : B Jardim Europa - Ver-o-Peso",
                "758 : Conj. Maguari - Ver-o-Peso",
                "761 : Satélite - Felipe Patroni",
                "762 : Satélite - Ver-o-Peso",
                "767 : Sideral - Pres. Vargas",
                "768 : LinSatélite - UFPA",
                "783 : Tenoné - Centro",
                "785 : Tenoné - Ver-o-Peso",
                "795 : Cabanagem - Pres. Vargas",
                "860 : Tapanã - UFPA",
                "861 : Tapanã - Ver-o-Peso",
                "862 : Tapanã - São Brás",
                "866 : Tapanã - Felipe Patroni",
                "869 : Tapanã - Presidente Vargas",
                "870 : Icoaraci - Paricás",
                "871 : Icoaraci - Ver-o-Peso (COHAB)",
                "872 : Icoaraci - Almirante Barroso (Paracuri II - Via BRT)",
                "873 : Icoaraci - Presidente Vargas (Paracuri)",
                "875 : Icoaraci - São Brás",
                "878 : Icoaraci - Cidade Nova (Via Satélite)",
                "879 : Outeiro - São Brás",
                "880 : Outeiro - Pres. Vargas",
                "881 : Águas Negras (Paricás) - Maracacuera",
                "882 : Outeiro - Brasília",
                "883 : Outeiro II - Terminal Mangueirão (Itaiteua)",
                "884 : Icoaraci - Marituba",
                "886 : Outeiro - Icoaraci",
                "888 : Icoaraci - Presidente Vargas (Via BRT)",
                "889 : Icoaraci - Centro (Via Arthur Bernardes)",
                "891 : Eduardo Angelim - Ver-o-Peso",
                "900 : Cidade Nova 4 - Ver-o-Peso",
                "901 : Cidade Nova 5 - Ver-o-Peso",
                "902 : Cidade Nova 6 - Pres. Vargas",
                "903 : PAAR - São Brás",
                "904 : Cidade Nova 8 - Pres. Vargas",
                "905 : Guajará - São Brás",
                "906 : Guajará - Ver-o-Peso",
                "907 : PAAR - Ver-o-Peso",
                "908 : PAAR - Ceasa",
                "910 : Marituba - Pátio Belém (Decouville)",
                "911 : Icuí - Ver-o-Peso",
                "912 : Castanheira - Pátio Belém",
                "913 : Marituba - São Brás",
                "914 : Marituba - UFPA",
                "915 : Águas Lindas - Pátio Belém",
                "916 : Águas Lindas - Ver-o-Peso",
                "917 : Distrito Industrial - Ver-o-Peso",
                "918 : Marituba - Ver-o-Peso",
                "919 : Curuçambá - Pátio Belém",
                "920 : Curuçambá - Ver-o-Peso",
                "921 : Curuçambá - Shopping Metrópole",
                "922 : Águas Lindas - Pres. Vargas",
                "923 : Ananindeua - Ver-o-Peso (Floresta Park)",
                "924 : Almir Gabriel - Pres. Vargas",
                "925 : Almir Gabriel - Ver-o-Peso",
                "926 : Almir Gabriel - Pátio Belém",
                "930 : Icuí - Pres. Vargas",
                "931 : Marituba - Ver-o-Peso (via BR-316)",
                "932 : Cidade Nova - UNAMA",
                "935 : Marituba - Pátio Belém (Cerâmica)",
                "936 : Marituba - Pátio Belém (Dom Aristides)",
                "937 : Marituba - Ver-o-Peso (Cerâmica)",
                "938 : Marituba - Pátio Belém (Direcional)",
                "939 : Marituba - Pátio Belém (Mario Couto)",
                "940 : Pedreira - Lomas (Linha B)",
                "941 : Marituba - Ver-o-Peso (via Alça Viária)",
                "942 : Marituba - Icoaraci",
                "948 : Curuçambá - Castanheira",
                "960 : Jaderlândia - Mangueirão",
                "964 : Jaderlândia - Ver-o-Peso",
                "970 : Mosqueiro - São Brás",
                "975 : Benevides - São Brás",
                "976 : Santa Bárbara - Ver-o-Peso",
                "977 : Santa Bárbara - São Brás",
                "980 : Ananindeua - Pres. Vargas (Águas Brancas)",
                "984 : 40 Horas - Pres. Vargas",
                "985 : 40 Horas - Ver-o-Peso",
                "986 : Jiboia Branca - Ver-o-Peso",
                "987 : 40 Horas - São Brás",
                "988 : Ananindeua - P. Vargas (Aurá)",
                "990 : Distrito Industrial - Pátio Belém",
                "991 : Curuçambá - UNAMA",
                "992 : Julia Seffer - Pres. Vargas",
                "993 : Julia Seffer - Pátio Belém",
                "996 : Águas Lindas - Terminal Mangueirão",
                "997 : Maguari - Doca",
                "998 : Maguari - Pátio Belém",
                "999 : Curuçambá - UFPA",
                "4009 : Distrito Industrial - Cidade Nova",
                "B001 : Marituba - Terminal Mangueirão (BRT)",
                "B002 : Ananindeua - Terminal Mangueirão (BRT)",
                "B003 : Águas Lindas - Terminal Mangueirão (Alimentadora)",
                "B004 : Curuçambá - Terminal Mangueirão (Alimentadora)",
                "TR10 : Troncal Mosqueiro - São Brás (BRT)",
                "TR20 : Troncal Icoaraci - São Brás (BRT)",
                "TR30 : Troncal Outeiro - São Brás (BRT)",
                "TR40 : Troncal Tapanã - Ver-o-Peso",
                "TR50 : Troncal Tenoné - Centro",
                "002 : Guanabara - Centro (Ananindeua)",
                "003 : Curuçambá - Cidade Nova",
                "008 : Águas Lindas - Centro (Ananindeua)",
                "010 : PAAR - Cidade Nova",
                "013 : Providência - Cidade Nova",
                "909 : Guajará - Castanheira",
                "928 : Marituba - Cidade Nova (via Ananindeua)",
                "933 : Icuí - Shopping Metrópole",
                "981 : Ananindeua - Ver-o-Peso (via Águas Brancas)",
                "005 : PAAR - Terminal Mangueirão (Alimentadora)",
                "006 : Icuí - Terminal Mangueirão (Alimentadora)",
                "007 : Guajará - Terminal Mangueirão (Alimentadora)",

        };
        return list;
    }
}
