package com.ia.recog_track;

import org.json.JSONObject;

import java.util.HashMap;
import java.util.Map;

public class Linhas {
    Linhas(){}
   public String[] getMap(){
        String[] list = {
                "548 : Marambaia - Ver-o-Peso",
                "754 : Jardim Sideral - Ver-o-Peso",
                "900 : Cidade Nova 4 - Ver-o-Peso",
                "901 : Cidade Nova 5 - Ver-o-Peso",
                "902 : Cidade Nova 6 - Pres. Vargas",
                "903 : PAAR - São Brás",
                "904 : Cidade Nova 8 - Pres. Vargas",
                "906 : Guajará - Ver-o-Peso",
                "907 : PAAR - Ver-o-Peso",
                "911 : Icuí - Ver-o-Peso",
                "930 : Icuí - Pres. Vargas",
                "932 : Cidade Nova - UNAMA",
                "960 : Jaderlândia - Mangueirão",
                "964 : Jaderlândia - Ver-o-Peso",
                "984 : 40 Horas - Pres. Vargas",
                "985 : 40 Horas - Ver-o-Peso",
                "986 : Jiboia Branca - Ver-o-Peso",
                "987 : 40 Horas - São Brás",
                "999 : Curuçambá - UFPA",
                "328 : Cipriano Santos - Presidente Vargas",
                "441 : Ceasa - Felipe Patroni",
                "442 : Ceasa - Ver-o-Peso",
                "546 : Sacramenta - Nazaré",
                "549 : Djalma Dutra",
                "755 : Sideral - Pátio Belém",
                "758 : Conj. Maguari - Ver-o-Peso",
                "767 : Sideral - Pres. Vargas",
                "783 : Tenoné - Centro",
                "785 : Tenoné - Ver-o-Peso",
                "795 : Cabanagem - Pres. Vargas",
                "871 : Icoaraci - Ver-o-Peso (COHAB)",
                "872 : Icoaraci - Almirante Barroso BRT",
                "881 : Águas Negras (Paricás) - Maracacuera",
                "883 : Outeiro II - Terminal Mangueirão (Itaiteua)",
                "227 : Sacramenta - Humaitá",
                "228 : Sacramenta - São Brás",
                "237 : Sacramenta - Pres. Vargas",
                "439 : Pedreira - Nazaré",
                "443 : Pedreira - Lomas (Linha A)",
                "445 : Pedreira - Lomas (Seletivo)",
                "634 : Marex - Arsenal",
                "635 : CDP/Providência - Ver-o-Peso",
                "935 : Marituba - Pátio Belém (Cerâmica)",
                "936 : Marituba - Pátio Belém (Dom Aristides)",
                "937 : Marituba - Ver-o-Peso (Cerâmica)",
                "938 : Marituba - Pátio Belém (Direcional)",
                "940 : Pedreira - Lomas (Linha B)",
                "878 : Icoaraci - Cidade Nova (Via Satélite)",
                "113 : Cremação - Estrada Nova",
                "114 : Cremação - Alcindo Cacela",
                "306 : UFPA - Pedreira",
                "307 : UFPA - Padre Eutíquio",
                "308 : UFPA - Alcindo Cacela",
                "309 : UFPA - Ver-o-Peso",
                "310 : UFPA - Pres. Vargas",
                "315 : UFPA - Centro Histórico",
                "914 : Marituba - UFPA",
                "757 : A Jardim Europa - Presidente Vargas",
                "757 : B Jardim Europa - Ver-o-Peso",
                "917 : Distrito Industrial - Ver-o-Peso",
                "919 : Curuçambá - Pátio Belém",
                "920 : Curuçambá - Ver-o-Peso",
                "923 : Ananindeua - Ver-o-Peso (Floresta Park)",
                "988 : Ananindeua - P. Vargas (Aurá)",
                "997 : Maguari - Doca",
                "998 : Maguari - Pátio Belém",
                "004 : Júlia Seffer - Cidade Nova",
                "014 : Águas Brancas - Cidade Nova",
                "884 : Icoaraci - Marituba",
                "975 : Benevides - São Brás",
                "975 : Benevides - Castanheira",
                "980 : Ananindeua - Pres. Vargas (Águas Brancas)",
                "990 : Distrito Industrial - Pátio Belém",
                "993 : Julia Seffer - Pátio Belém",
                "4009 : xDistrito Industrial - Cidade Nova",
                "311 : Guamá - Conselheiro",
                "312 : Guamá - Montepio",
                "314 : Guamá - Ver-o-Peso",
                "316 : Guamá - Pres. Vargas",
                "317 : Guamá - Pátio Belém",
                "631 : Marex - Ver-o-Peso",
                "636 : Marex - Pres. Vargas",
                "320 : UFPA - Tamoios",
                "446 : João Paulo II - Ver-o-Peso",
                "632 : Marex - Felipe Patroni",
                "318 : Arsenal",
                "328 : Cipriano Santos - Presidente Vargas",
                "441 : Ceasa - Felipe Patroni",
                "442 : Ceasa - Ver-o-Peso",
                "910 : Marituba - Pátio Belém (Decouville)",
                "918 : Marituba - Ver-o-Peso",
                "924 : Almir Gabriel - Pres. Vargas",
                "925 : Almir Gabriel - Ver-o-Peso",
                "926 : Almir Gabriel - Pátio Belém",
                "939 : Marituba - Pátio Belém (Mario Couto)",
                "941 : Marituba - Ver-o-Peso (via Alça Viária)",
                "942 : Marituba - Icoaraci",
                "992 : Julia Seffer - Pres. Vargas",
                "768 : LinSatélite - UFPA",
                "915 : Águas Lindas - Pátio Belém",
                "916 : Águas Lindas - Ver-o-Peso",
                "922 : Águas Lindas - Pres. Vargas",
                "996 : Águas Lindas - Terminal Mangueirão",
                "001 : Saré - 40 Horas",
                "015 : 40 Horas - Castanheira",
                "862 : Desconhecido",
                "011 : Desconhecido",
                "021 : Desconhecido",
                "035 : Desconhecido",
                "058 : Desconhecido",
                "253 : Desconhecido",
                "005 : Desconhecido",
                "021 : Desconhecido",

//253//209//058//035//021//011
// 862//039//089//005//021//181//137//365//862//638//003//66408/213//037//151//131/633
//181
        };
        return list;
    }
}
